# Generated by Django 5.2.7 on 2025-10-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='C:\\mini project\x0bigilai\x08ackend\\profile_photos\\default.png', null=True, upload_to='profile_photos/'),
        ),
    ]
