# Generated by Django 5.2.7 on 2025-10-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='staff_id',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
