# Generated by Django 5.2.7 on 2025-10-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_photos/default.png', null=True, upload_to='profile_photos/'),
        ),
    ]
