# Generated by Django 5.2.7 on 2025-11-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='id',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='room_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
