# Generated by Django 5.2.7 on 2025-11-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chatroom_id_remove_message_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='case',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='mentioned_case',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('mention', 'Mention'), ('message', 'Message')], default='message', max_length=20),
        ),
    ]
