# Generated by Django 5.2.7 on 2025-10-14 10:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=200)),
                ('primary_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('district', models.PositiveSmallIntegerField()),
                ('ward', models.PositiveSmallIntegerField()),
                ('location_description', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Closed', 'Closed'), ('Reopened', 'Reopened')], default='Open', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('investigator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigated_cases', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CriminalRecord',
            fields=[
                ('criminal_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=200)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('district', models.PositiveSmallIntegerField(help_text='District number (1–14)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(14)])),
                ('offenses', models.TextField()),
                ('photo', models.ImageField(blank=True, help_text='Upload an image of the criminal', null=True, upload_to='criminal_photos/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criminal_records', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('evidence_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_evidence', models.CharField(choices=[('DNA', 'DNA'), ('Fingerprint', 'Fingerprint'), ('Weapon', 'Weapon'), ('Document', 'Document'), ('Other', 'Other')], default='Other', max_length=100)),
                ('details', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='evidences/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='SuspectPrediction',
            fields=[
                ('prediction_id', models.AutoField(primary_key=True, serialize=False)),
                ('suspect_name', models.CharField(max_length=200)),
                ('probability', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('witness_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('statement', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='cases.case')),
            ],
        ),
    ]
