# Generated by Django 5.2.7 on 2025-10-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='witness',
            name='contact_info',
            field=models.CharField(blank=True, help_text='Phone number or email of the witness', max_length=100, null=True),
        ),
    ]
