# Generated by Django 5.2.5 on 2025-09-03 08:48

from django.db import migrations


def backfill_owner(apps, schema_editor):
    Case = apps.get_model('cases', 'Case')
    User = apps.get_model('auth', 'User')  # or refer to your custom user model

    default_user = User.objects.first()  # choose based on your logic

    # Update all cases with null owner
    Case.objects.filter(owner__isnull=True).update(owner=default_user)

class Migration(migrations.Migration):
    dependencies = [
        ('cases', '0001_initial'),  # adjust to match previous migration
    ]

    operations = [
        migrations.RunPython(backfill_owner),
    ]
