# Generated by Django 5.2.7 on 2025-11-02 14:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_witness_contact_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('criminal_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=200)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('district', models.PositiveSmallIntegerField(help_text='District number (1–14)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(14)])),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='criminal_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='criminalrecord',
            old_name='criminal_id',
            new_name='record_id',
        ),
        migrations.RemoveField(
            model_name='criminalrecord',
            name='age',
        ),
        migrations.RemoveField(
            model_name='criminalrecord',
            name='district',
        ),
        migrations.RemoveField(
            model_name='criminalrecord',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='criminalrecord',
            name='person_name',
        ),
        migrations.RemoveField(
            model_name='criminalrecord',
            name='photo',
        ),
        migrations.AlterField(
            model_name='criminalrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='criminalrecord',
            name='suspect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='cases.criminal'),
            preserve_default=False,
        ),
    ]
