# Generated by Django 5.2.7 on 2025-11-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_criminal_rename_criminal_id_criminalrecord_record_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criminal',
            old_name='age',
            new_name='criminal_age',
        ),
        migrations.RenameField(
            model_name='criminal',
            old_name='district',
            new_name='criminal_district',
        ),
        migrations.RenameField(
            model_name='criminal',
            old_name='gender',
            new_name='criminal_gender',
        ),
        migrations.RenameField(
            model_name='criminal',
            old_name='person_name',
            new_name='criminal_name',
        ),
        migrations.AddField(
            model_name='suspectprediction',
            name='suspect_id',
            field=models.IntegerField(blank=True, help_text="Predicted suspect's ID", null=True),
        ),
    ]
