# Generated by Django 5.2.5 on 2025-09-03 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_owner'),
        ('cases', '0003_backfill_owner'),
    ]

    operations = [
    ]
