# Generated by Django 5.2.7 on 2025-11-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_rename_age_criminal_criminal_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='local_governance',
            field=models.CharField(choices=[('Panchayat', 'Panchayat'), ('Municipal Corporation', 'Municipal Corporation')], default='Panchayat', max_length=30),
        ),
    ]
