# Generated by Django 5.2.7 on 2025-11-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_local_governance'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='governance_name',
            field=models.CharField(blank=True, help_text='Name of the Panchayat or Corporation', max_length=200),
        ),
    ]
