# Generated by Django 5.2.5 on 2025-09-05 09:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_alter_case_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criminalrecord',
            old_name='past_offenses',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='evidence',
            old_name='description',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='evidence',
            old_name='evidence_type',
            new_name='type_of_crime',
        ),
        migrations.RemoveField(
            model_name='case',
            name='date_reported',
        ),
        migrations.RemoveField(
            model_name='case',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='case',
            name='title',
        ),
        migrations.RemoveField(
            model_name='criminalrecord',
            name='associated_cases',
        ),
        migrations.RemoveField(
            model_name='criminalrecord',
            name='person_name',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='file',
        ),
        migrations.RemoveField(
            model_name='witness',
            name='name',
        ),
        migrations.AddField(
            model_name='case',
            name='crime_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='case',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='criminalrecord',
            name='case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='criminal_records', to='cases.case'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='cases.case'),
        ),
    ]
