# Generated by Django 5.2.7 on 2025-11-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_case_governance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='type_of_evidence',
            field=models.CharField(default='Other', max_length=100),
        ),
    ]
