# Generated by Django 5.2.5 on 2025-09-05 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_rename_past_offenses_criminalrecord_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='criminalrecord',
            old_name='details',
            new_name='offenses',
        ),
        migrations.AddField(
            model_name='case',
            name='investigator',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='case',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='title',
            field=models.CharField(default='Untitled Case', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criminalrecord',
            name='person_name',
            field=models.CharField(default='Ted Bundy', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evidence',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='evidences/'),
        ),
        migrations.AddField(
            model_name='witness',
            name='name',
            field=models.CharField(default='sara michael', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='crime_id',
            field=models.CharField(default='0001', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Closed', 'Closed'), ('Reopened', 'Reopened')], default='Open', max_length=50),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='cases.case'),
        ),
    ]
