# Generated by Django 5.2.7 on 2025-11-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_alter_evidence_type_of_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='witness',
            name='aadhaar_number',
            field=models.CharField(default='ram', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
