# Generated by Django 5.2.5 on 2025-09-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_rename_details_criminalrecord_offenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalrecord',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload an image of the criminal', null=True, upload_to='criminal_photos/'),
        ),
    ]
