# Generated by Django 5.2.7 on 2025-11-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_witness_aadhaar_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='arrested',
            field=models.BooleanField(default=False),
        ),
    ]
