# Generated by Django 5.2.5 on 2025-09-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_criminalrecord_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidence',
            old_name='type_of_crime',
            new_name='type_of_evidence',
        ),
        migrations.AddField(
            model_name='case',
            name='type_of_crime',
            field=models.CharField(default='Robbery', max_length=100),
            preserve_default=False,
        ),
    ]
