# Generated by Django 5.2.7 on 2025-11-28 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_case_arrested'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criminalrecord',
            options={'verbose_name': 'Criminal Record', 'verbose_name_plural': 'Criminal Records'},
        ),
        migrations.RemoveField(
            model_name='case',
            name='arrested',
        ),
        migrations.AddField(
            model_name='case',
            name='arrest_status',
            field=models.CharField(choices=[('Not Arrested', 'Not Arrested'), ('Arrested', 'Arrested')], default='Not Arrested', max_length=20),
        ),
        migrations.AlterField(
            model_name='criminalrecord',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criminal_records', to='cases.case', verbose_name='Associated Case'),
        ),
        migrations.AlterField(
            model_name='criminalrecord',
            name='suspect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='cases.criminal', verbose_name='Criminal Suspect'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_number'], name='cases_case_case_nu_a07304_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', 'district'], name='cases_case_status_dc8af3_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['created_at'], name='cases_case_created_a9dee7_idx'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(fields=('case_number',), name='unique_case_number'),
        ),
        migrations.AddConstraint(
            model_name='criminal',
            constraint=models.UniqueConstraint(fields=('aadhaar_number',), name='unique_criminal_aadhaar'),
        ),
    ]
