# Generated by Django 5.2.5 on 2025-09-09 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_rename_type_of_crime_evidence_type_of_evidence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='title',
            new_name='case_number',
        ),
    ]
