# Generated by Django 5.2.7 on 2025-11-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_alter_criminalrecord_options_remove_case_arrested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SuspectPrediction',
        ),
    ]
