# Generated by Django 5.2.7 on 2025-11-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_criminal_date_of_birth_delete_suspectprediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminal',
            name='criminal_age',
        ),
    ]
