# Generated by Django 5.2.7 on 2025-11-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_remove_criminal_criminal_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witness',
            name='statement',
            field=models.FileField(blank=True, help_text='Audio or video recording of the witness statement', null=True, upload_to='witness_statements/'),
        ),
    ]
