# Generated by Django 5.2.7 on 2025-12-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_alter_witness_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalrecord',
            name='involvement_type',
            field=models.CharField(choices=[('SUSPECT', 'Suspect'), ('ACCUSED', 'Accused'), ('CONVICTED', 'Convicted'), ('WANTED', 'Wanted')], default='SUSPECT', max_length=50),
        ),
    ]
