# Generated by Django 5.2.7 on 2025-12-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_criminalrecord_involvement_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criminalrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Criminal Record', 'verbose_name_plural': 'Criminal Records'},
        ),
        migrations.AddField(
            model_name='criminalrecord',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open Investigation'), ('CLOSED', 'Case Closed'), ('PENDING', 'Pending Trial'), ('SOLVED', 'Solved')], default='OPEN', max_length=50),
        ),
    ]
